config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#splash'
  
  resources :users
  resources :groups, :path => "categories" do 
    resources :expenses, :path => "transactions"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless current_user.present? # logged in user only can access the app (not guest)

    can(:manage, Group, user:)
    can(:manage, Expense, user:)
    can :manage, GroupExpense do |category_transaction|
      category_transaction.group.user == user
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: { scope: :author, message: 'You already have an transaction with this name' }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 },
                   uniqueness: { scope: :author, message: 'You have already Category with this name' }
  validates :icon, presence: true, length: { maximum: 250 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  def total_transactions
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :password, presence: true, length: { maximum: 20 }

  has_many :groups, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:splash]

  def after_sign_in_path_for(_resource)
    groups_url
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expenses, only: %i[edit update destroy]
  before_action :set_users, only: %i[index edit create update destroy]
  before_action :set_groups, only: %i[index new edit create update destroy]

  def index
    @expenses = @group.expenses.order(created_at: 'desc')
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(author: @author, **expenses_params)
    if @expense.save
      @group_expense = GroupExpense.create(group: @group, expense: @expense)
      flash[:notice] = 'Expense has been successfully created.'
      redirect_to group_expenses_url(@group)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def destroy
    return unless @expense.destroy

    flash[:notice] = 'Expense has been successfully destroyed.'
    redirect_to group_expenses_url(@group)
  end

  def update
    if @expense.update(expenses_params)
      flash[:notice] = 'Expense has been successfully updated.'
      redirect_to group_expenses_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_groups
    @group = set_users.groups.find(params[:group_id])
  end

  def set_expenses
    @expense = set_users.expenses.find(params[:id])
  end

  def set_users
    @author = current_user
  end

  def expenses_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_users, only: %i[index edit create update destroy]
  before_action :set_groups, only: %i[edit update destroy]

  def index
    @groups = @author.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(author: @author, **groups_params)

    if @group.save
      flash[:notice] = 'Group has been successfully created.'
      redirect_to groups_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @group.destroy

    flash[:notice] = 'Group has been successfully destroyed.'
    redirect_to groups_url
  end

  def edit; end

  def update
    if @group.update(groups_params)
      flash[:notice] = 'Group has been successfully updated.'
      redirect_to groups_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_groups
    @group = set_users.groups.find(params[:id])
  end

  def set_users
    @author = current_user
  end

  def groups_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_categories, only: %i[show index]
  before_action :set_user, only: %i[show edit update destroy]

  def splash
    if current_user
      flash[:notice] = "You have already sign in as, #{current_user.name}"
      redirect_to groups_url
    else
      render :splash_page
    end
  end

  def index
    @users = User.all
  end

  def show; end

  private

  def redirect_to_categories
    redirect_to groups_url
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="my-5 flex items-center justify-between">
  <div class="flex gap-3 items-center">
    <div class="flex gap-2 items-center">
      <%= image_tag @group.icon, class: "rounded-full object-cover w-20 h-20 " %>
      <%= expense.name %>
      <span class="font-bold">$<%= expense.amount %> </span>
    </div>
  </div>
  <% if action_name != "show" %>
    <div class="flex gap-2">
    <%= link_to edit_group_expense_path(@group,expense), class: "rounded-lg px-1 py-1 inline-block font-medium bg-gray-100" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-amber-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
      </svg>

    <% end %>
    <%= button_to group_expense_path(@group, expense), method: :delete, class: "rounded-lg px-1 py-1 inline-block font-medium bg-gray-100" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-red-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
      </svg>
    <% end %>
    </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? group_expense_path(@group, expense) : group_expenses_path(@group)}", class: "contents") do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="bg-red-50 py-2 px-3 font-medium rounded-lg text-red-500  mt-3">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block rounded-md border border-gray-200 outline-none shadow py-2 mt-2 px-3 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: ".01", class: "block shadow border-gray-200 outline-none rounded-md border mt-2 px-3 py-2 w-full" %>
  </div>

  <div class="flex justify-center mt-10 bg-second fixed left-0 right-0 bottom-0 py-3">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "w-[80%] uppercase font-medium px-5 py-2 bg-second border text-white block" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="md:w-2/3 mx-auto w-full">
  <h1 class="text-4xl font-bold">Edit Expense</h1>

  <%= render "form", expense: @expense %>
  <%= link_to "Back to expenses", group_expenses_path, class: "ml-2 rounded-lg inline-block font-medium py-3 px-5 bg-gray-100" %>
</div>

app/views/expenses/index.html.erb
<div class="w-full">
 <% if flash[:success] %>
    <p class="py-2 px-3 font-medium rounded-lg text-green-500 inline-block bg-green-50 mb-5" id="notice"><%= flash[:success] %></p>
  <% end %> 
  <div class="flex items-center justify-between">
    <h1 class=" text-4xl font-bold"><%= "#{@group.name}' " %>Transactions</h1>
  </div>
  <div id="expenses" class="min-w-full">
    <%= render @expenses %>
  </div>
</div>
<div class="bg-second flex justify-center fixed left-0 right-0 bottom-0 py-3">
  <%= link_to new_group_expense_path, class: "w-[80%] flex px-5 bg-second items-center justify-center border text-white gap-2 py-2 block font-medium" do %>
    <span>New transaction</span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
    </svg>
  <% end %>
</div>

app/views/expenses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Transaction</h1>

  <%= render "form", expense: @expense %>
  
  <%= link_to 'Back to expenses', group_expenses_path, class: "ml-2 px-5 bg-gray-100 rounded-lg py-3 font-medium inline-block" %>
</div>

app/views/expenses/show.html.erb
<div class="w-full flex mx-auto md:w-2/3">
  <div class="mx-auto">
 <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 text-green-500 font-medium rounded-lg mb-5 inline-block" id="notice"><%= notice %></p>
    <% end %> 
    <%= render @expense %>
    <%= link_to 'Edit this expense', edit_group_expense_path(@group, @expense), class: "mt-2 rounded-lg inline-block font-medium px-5 py-3 bg-gray-100" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this expense', group_expense_path(@group, @expense), method: :delete, class: "mt-2 bg-gray-100 font-medium rounded-lg py-3 px-5" %>
    </div>
    <%= link_to 'Back to expenses', group_expenses_path, class: "ml-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 font-medium rounded-lg text-red-500 py-2 px-3 mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow outline-none rounded-md border-gray-200 border px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :icon %>
    <%= form.text_field :icon, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
  </div>

  <div class="mt-10 bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center items-center">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "w-[20%] py-2 px-5 bg-second  text-white block uppercase font-medium" %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-white">
      <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 3.75V16.5L12 14.25 7.5 16.5V3.75m9 0H18A2.25 2.25 0 0120.25 6v12A2.25 2.25 0 0118 20.25H6A2.25 2.25 0 013.75 18V6A2.25 2.25 0 016 3.75h1.5m9 0h-9" />
    </svg>

  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="flex my-5 justify-between items-center">
  <div class="flex gap-3 items-center">
    <%= link_to  group_expenses_path(group), class: "flex gap-3 items-center" do %>
      <%= image_tag group.icon, class: "rounded-full object-cover w-20 h-20" %>
      <span> <%= group.name %> </span>
      <span class="font-bold"> $<%= group.total_transactions %> </span>
    <% end %>
  </div>
  <% if action_name != "show" %>
    <div class="flex gap-2">
    <%= link_to edit_group_path(group), class: "rounded-lg py-1 px-1 inline-block font-medium bg-gray-100" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-amber-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
      </svg>
    <% end %>
    <%= button_to group_path(group), method: :delete, class: "rounded-lg py-1 px-1 inline-block font-medium bg-gray-100" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-red-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
      </svg>

    <% end %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edit <%=@group.name %></h1>

  <%= render "form", group: @group %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 inline-block font-medium px-5 bg-gray-100" %>
</div>

app/views/groups/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl font-sans">Categories</h1>
  </div>

  <div id="groups" class="min-w-full">
    <%= render @groups %>
  </div>
  
</div>
<div class="bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center">
  <%= link_to new_group_path, class: "w-[80%] flex items-center justify-center gap-2 py-2 px-5 bg-second border text-white block font-medium" do %>
    <span> <%= 'New Category' %> </span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
    </svg>

  <% end %>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Category</h1>

  <%= render "form", group: @group %>
  <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if flash[:notice] %>
      <p class="py-2 px-3 bg-green-50 mb-5 inline-block font-medium rounded-lg text-green-500" id="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= render @group %>
    <%= link_to 'Edit group', edit_group_path(@group), class: "mt-2 rounded-lg bg-gray-100 inline-block py-3 px-5 font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this group', group_path(@group), method: :delete, class: "mt-2 bg-gray-100 font-medium rounded-lg py-3 px-5" %>
    </div>
    <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg inline-block font-medium py-3 px-5 bg-gray-100 " %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="fixed mb-5 right-0 bg-main pt-5 left-0 px-3 top-0 z-50">
  <div class="top-nav flex justify-between items-center border-b-2 pb-2">
      <% if controller_name == 'groups' and action_name == 'index' %>
        <div class="hamburger-menu">
          <svg class="stroke-white h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </div>
      <% elsif controller_name == 'groups' and action_name != 'index' %>
        <div class="back-btn">
          <%= link_to groups_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>
          <% end %>
        </div>
      <% elsif controller_name == 'expenses' %>
        <div class="back-btn">
          <%= link_to "#{action_name == 'index' ? groups_path : group_expenses_path}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>
          <% end %>
        </div>
      <% end %>
      <h1 class="text-white text-2xl m-0 uppercase">
        <% if controller_name == 'expenses' %>
          <%= 'Transactions' %>
        <% else %>
          <%= 'Categories' %>
        <% end %>
      </h1>
      <div class="search">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8 stroke-white">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 15.75l-2.489-2.489m0 0a3.375 3.375 0 10-4.773-4.773 3.375 3.375 0 004.774 4.774zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
  </div>
  <div class="my-3 flex justify-between">
    <span class="bg-white py-1 px-2 w-max rounded-lg text-main font-semibold grid grid-cols-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
    </svg>
      <%= current_user.name %>
      <% if controller_name == 'expenses' %>
        : $<%= @group.total_transactions %>
      <% end %>
    </span>
    <%= button_to destroy_user_session_path, method: :delete, class: 'flex items-center gap-2' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-white">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
      </svg>
      <span class="text-white font-semibold">Log Out</span>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'https://www.pngarts.com/files/12/Budget-Logo-PNG-Download-Image.png' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% elsif alert.present? %>
       <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
      <% end %>
      <% if current_user %>
        <%= render 'layouts/navbar' %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/users/splash_page.html.erb
<div class="absolute top-8 flex items-center">
  <%= image_tag 'https://gifimage.net/wp-content/uploads/2018/06/welcome-gif-image-7.gif', class: 'h-10 w-[150px]' %>
</div>
<%= image_tag "https://www.pngarts.com/files/12/Budget-Logo-PNG-Download-Image.png", class: 'md:max-w-md self-center h-[200px] w-[200px]' %>

<div class="row-span-3 hover:row-span-4 actions absolute w-10/12 bottom-4 self-center">
  <%= link_to new_user_session_path, class: 'group rounded-lg mb-4 flex items-center border hover:border-main bg-main p-3 justify-center hover:bg-transparent' do %>
    <span class="text-white uppercase group-hover:text-main font-semibold">Log In</span>
  <% end %>
  <%= link_to new_user_registration_path, class: 'group rounded-lg flex items-center bg-main border hover:border-main p-3 hover:bg-transparent justify-center' do %>
    <span class="group-hover:text-main text-white uppercase font-semibold">Sign Up</span>
  <% end %>
</div>